version: '3'
services:
    postgres:
      image: postgres:11
      environment:
        POSTGRES_DB: shortler_prod
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432

    influxdb:
      image: influxdb:1.5
      environment:
        INFLUXDB_DB: shortler_clicks
        INFLUXDB_USER: shortler
        INFLUXDB_USER_PASSWORD: shortler
      ports:
        - 8086:8086

    influxdbdev:
      image: influxdb:1.5
      environment:
        INFLUXDB_DB: shortler_clicks
        INFLUXDB_USER: shortler
        INFLUXDB_USER_PASSWORD: shortler
      ports:
        - 8087:8086

    shortler:
      image: "shortler:${VSN}"
      ports:
        - 8888:8888
      depends_on:
        - postgres
